### ISSUE TITLE
Typo in 04_mnist_basics notebook at Summarizing gradient descent section

### ISSUE THREAD

**Issue by Geethasaikrishna** [fastai/fastbook#142]
**Text in the notebook**: Our weights need to be improved. _To do this, we take a few data items (such as images) **that** and feed them to our model_

**Issue** : In the italic- highlighted text above, seems like word **that**  is not fitting in context of sentence. Two probable cases, may be something is missed to be written after **that** or **that** is actually a typo

**Comment by jph00** [comment]
We'd be happy to take a PR on any issues you find in the text :)
