### ISSUE TITLE
Strange pattern of missing sentences in notebooks

### ISSUE THREAD

**Issue by riven314** [fastai/fastbook#149]
I am reviewing a few chapters of the notebooks. I am not sure if it is a bug or something, but I consistently noticed that whenever there is a sentence with the words **"in <"**, words/ sentences right after that disappear. 

Here are a few examples:

**example 1: from 07_sizing_and_tta.ipynb**

![7](https://user-images.githubusercontent.com/21143399/80495480-8e160c80-899a-11ea-984b-05b01aac1fc4.JPG)

**example 2: from 05_pet_breeds.ipynb**

![5](https://user-images.githubusercontent.com/21143399/80495504-979f7480-899a-11ea-9cbc-a9f07539314c.JPG)

**Remarks**
1. I am viewing the notebooks directly in github
2. When I view the page in raw format, sentences that are missed in markdown are actually present.

It is a bit strange that it happens in many places. Would like to see if others could confirm the phenomenon.

**Comment by sgugger** [comment]
> I am viewing the notebooks directly in github

You should not do that. Github is not a proper notebook renderer. Use [nbviewer](https://nbviewer.jupyter.org/) to get them to show properly if you don't have a local client.

Note that in any case, those references will appear as <> (you'll just see the rest of the markdown).
