### ISSUE TITLE
Can't pickle local object 'parallel_gen.<locals>.f' in 01_intro

### ISSUE THREAD

**Issue by hummus1220** [fastai/fastbook#192]
When I run the following code(from ch1 intro), I get the error message.

from fastai2.text.all import *

dls = TextDataLoaders.from_folder(untar_data(URLs.IMDB), valid='test')
learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.fine_tune(4, 1e-2)

AttributeError: Can't pickle local object 'parallel_gen.<locals>.f'

Would you please let me know how to fix this problem? Thanks in advance.

**Comment by jph00** [comment]
That should be fixed with the latest version of fastai2 now.

**Comment by AniTho** [comment]
After upgrading to latest version fastai2 version: 0.0.28, the error is thrown as broken pipe error
**BrokenPipeError**                          
 Traceback (most recent call last)
<ipython-input-2-0be5580d86a8> in <module>
      2 
      3 path = untar_data(URLs.IMDB, dest='../data/3')
----> 4 dls = TextDataLoaders.from_folder(path, valid='test', bs = 16, num_workers = 0)
      5 learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
      6 learn.fine_tune(4, 1e-2)

And following is the command prompt output:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Softwares\Anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Softwares\Anaconda\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\Softwares\Anaconda\lib\site-packages\fastcore\utils.py", line 782, in <module>
    IN_IPYTHON,IN_JUPYTER,IN_COLAB,IN_NOTEBOOK = in_ipython(),in_jupyter(),in_colab(),in_notebook()
  File "D:\Softwares\Anaconda\lib\site-packages\fastcore\utils.py", line 774, in in_jupyter
    return get_ipython().__class__.__name__ == 'ZMQInteractiveShell'
NameError: name 'get_ipython' is not defined

Thanks in advanced.
