### ISSUE TITLE
subclasses Tuple in SiameseImage(Tuple) of 11_midlevel_data

### ISSUE THREAD

**Issue by AliceSum** [fastai/fastbook#205]
However, the Tuple class does not exist in fastaiv2 or some comments said it is deleted.

**Comment by rjdp** [comment]
whats the woraround to this ? thanks :)

**Comment by JonathanSum** [comment]
https://github.com/JonathanSum/Fastbook_colab/blob/master/11_midlevel_data.ipynb

**Comment by rjdp** [comment]
Thanks :) , I wonder why this is not fixed in this repo

**Comment by JonathanSum** [comment]
I have made pull request on this and another one, but they are not mergered.
