### ISSUE TITLE
References are empty and unfollowable

### ISSUE THREAD

**Issue by Qumeric** [fastai/fastbook#208]
I am not sure if it's a problem with notebooks or a problem with GitHub rendering but I cannot see links in notebooks. They are shown as "<". See screenshot attached. Chrome 84, macOS.
<img width="1109" alt="Screenshot 2020-08-22 at 02 09 59" src="https://user-images.githubusercontent.com/3511113/90945407-9ea43400-e41c-11ea-9044-f4f7fe34990c.png">

**Comment by jph00** [comment]
The references are only for the paper book.
