### ISSUE TITLE
Not working in Colab, but Ok with Binder

### ISSUE THREAD

**Issue by buzem** [fastai/fastbook#219]
While running the 5th notebook, I got error from this line : 

dls1 = dblock1.dataloaders([(Path.cwd()/'images'/'grizzly.jpg')]*100, bs=8)

[Errno 2] No such file or directory: '/content/images/grizzly.jpg'

**Comment by DicksonWu654** [comment]
Hi, I think it's because you don't have the image called "grizzly.jpg" inside /content/images. 

To fix it, you can just download an image of a grizzly, name it "grizzly.jpg". Create a folder inside content called images. Then pop the image into that folder. That should fix it!

**Comment by buzem** [comment]
Yeah, i know this manual solution however I did want to make the notebooks error-free for other users.
