### ISSUE TITLE
Add bibtex entry to README?

### ISSUE THREAD

**Issue by hallvagi** [fastai/fastbook#227]
Maybe add a bibtex entry to README.md for citations?

@book{gugger2020deep,
  title={Deep Learning for Coders with Fastai and Pytorch: AI Applications Without a PhD},
  author={Gugger, S. and Howard, J.},
  isbn={9781492045526},
  url={https://books.google.no/books?id=xd6LxgEACAAJ},
  year={2020},
  publisher={O'Reilly Media, Incorporated}
}

**Comment by jph00** [comment]
Sure will do
