### ISSUE TITLE
AttributeError in 07_sizing_and_tta.ipynb in Colab and Gradient

### ISSUE THREAD

**Issue by MarkB2** [fastai/fastbook#234]
### In Test Time Augmentation 
`AttributeError                            Traceback (most recent call last)

<ipython-input-10-116f96bffa70> in <module>()
----> 1 preds,targs = learn.tta()
      2 accuracy(preds, targs).item()

13 frames

/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py in update(self, val)
     57         elif val <= self.first_its or val >= self.last_v + self.wait_for or val >= self.total:
     58             cur_t = time.time()
---> 59             avg_t = (cur_t - self.start_t) / val
     60             self.wait_for = max(int(self.update_every / (avg_t+1e-8)),1)
     61             self.pred_t = avg_t * self.total

AttributeError: 'NBProgressBar' object has no attribute 'start_t'

`

**Comment by jph00** [comment]
Are you still seeing this in the latest version of the book and fastai?

**Comment by MarkB2** [comment]
It's OK now, thanks.
