### ISSUE TITLE
Fastbook

### ISSUE THREAD

**Issue by jeremy19877** [fastai/fastbook#238]

**Comment by DicksonWu654** [comment]
I'm getting the same error too. I can't run this code in Google Colab:
```
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()
```

The error message is: ModuleNotFoundError: No module named 'fastbook'

I've tried resetting the notebook, tried creating an new notebook. Tried running this code too beforehand: pip install fastai --upgrade

Thanks!
