### ISSUE TITLE
cp8 - runtime error when creating TabularPandas 

### ISSUE THREAD

**Issue by jhrun** [fastai/fastbook#249]
I encountered `TypeError: Object with dtype category cannot perform the numpy op subtract` when running the following code snippet in Chapter 8, section "Using a Neural Network". 

```python
procs_nn = [Categorify, FillMissing, Normalize]
to_nn = TabularPandas(df_nn_final, procs_nn, cat_nn, cont_nn,
                      splits=splits, y_names=dep_var)
```

The code runs ok when `Normalize` is removed from `procs_nn`. 

@jph00 Am I missing more preprocessing steps or is the error a result of bugs in `fastai` ? Thanks in advance !

**Comment by jhrun** [comment]
I'm running `fastai v2.0.8` installed from anaconda.

**Comment by JDuchniewicz** [comment]
I can confirm the issue persists with v2.0.15

**Comment by kozer** [comment]
Do we have any news on that?

**Comment by jph00** [comment]
Should be fixed now.
