### ISSUE TITLE
Notebook error - 05_pet_breeds

### ISSUE THREAD

**Issue by weltonrodrigo** [fastai/fastbook#251]
The cell in presizing has a runtime error:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-90ae321055d3> in <module>()
      5                    get_y=parent_label,
      6                    item_tfms=Resize(460))
----> 7 dls1 = dblock1.dataloaders([(Path.cwd()/'images'/'grizzly.jpg')]*100, bs=8)
      8 dls1.train.get_idxs = lambda: Inf.ones
      9 x,y = dls1.valid.one_batch()

13 frames
/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2807 
   2808     if filename:
-> 2809         fp = builtins.open(filename, "rb")
   2810         exclusive_fp = True
   2811 

FileNotFoundError: [Errno 2] No such file or directory: '/content/images/grizzly.jpg'
```

Maybe change it to use the dataloader created in the beginning of the notebook?

Thank you for the amazing work, guys!

**Comment by weltonrodrigo** [comment]
Another one.

a typo on 

> The *soltuon* does not require any advanced maths, giant computing resources, huge datasets, or anything else that would make it inaccessible to any curious researcher.

Guys, can you point me some doc about how I can do PRs with jupyter notebooks? Is there something special or I just fork this, run in my machine and commit with cell results?

**Comment by TannerGilbert** [comment]
If you only change the markdown or don't run the code you can just commit as usual. If you run any cells you should clear the cells. For that check out:
- https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md
- https://github.com/kynan/nbstripout

**Comment by jph00** [comment]
I've added a comment to let people know to pop an image in that location.
