### ISSUE TITLE
fine_tune runs forever with gpu version of fastai

### ISSUE THREAD

**Issue by subratac** [fastai/fastbook#252]
According to the documentation, "fine_tune"  from the example in Chapter 1 of the book should take a few minutes. It is running for more than 30 minutes on my MacBookPro with the following configuration. (2.3GHz, 8 Core, 16GB RAM 2400 MHz DDR4, Radeon Pro 560X 4GB, Intel UHD Graphics 630 1536 MB)

I have installed the gpu version of fasiai. Could someone help?
Thanks
Sub
=====

#id first_training
#caption Results from the first training
# CLICK ME
from fastai.vision.all import *
path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)

**Comment by subratac** [comment]
This is how long it took on my Mac:

epoch | train_loss | valid_loss | error_rate | time
--         --               | --              | --               | --
0         | 0.139242 | 0.033724 | 0.009472 | 26:43

epoch	train_loss	  valid_loss	error_rate	time
0	       0.052510	0.019551	0.008119	              35:40

**Comment by sirbots** [comment]
While you can train deep learning models on a MacBook with a GPU, you will get much faster results using a hosted GPU from a service like Gradient. You can view several options for using a cloud GPU [server here on the course page](https://course19.fast.ai/start_gradient.html).

**Comment by subratac** [comment]
Thanks, Robert. I wanted to make sure that if it is something I did not install correctly. We already have the resnet model and we are just fine tuning and it was taking close to 40 minutes versus 14 seconds it showed in the book.

**Comment by sirbots** [comment]
No problem! You can also replace "resnet34" with "resnet18" and it will train a bit faster. The results may not be as good but for simple classification models, they should be pretty good!

**Comment by enigma6174** [comment]
Hi I am facing the exact same issue with the same code in the same chapter. For me it took 22 minutes!! I am using **Ubuntu 20** with **NVIDIA RTX 2070** and the latest **CUDA (10.2)** drivers. My Python version is **3.8.x**.   
This same code using the same model and data (resnet34 on PETs dataset) used to take **not more than 1 minute** in the same configuration when I used fastai v1 (in fact I just checked again to be sure and also ran a similar code using pure PyTorch and all of this was very very fast)! Could anyone please highlight what is going wrong here?
