### ISSUE TITLE
Mention that search engines API can yield NSFW results?

### ISSUE THREAD

**Issue by dgellow** [fastai/fastbook#253]
Hi @jph00,

I'm reading through your book, and I just had an unpleasant experience. In the section "Training Your Model, and Using It to Clean Your Data" of the second chapter ([link](https://render.githubusercontent.com/view/ipynb?commit=c68fc90f2d9d4cbb8dbe9845d12c26fc699002b2&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6661737461692f66617374626f6f6b2f633638666339306632643964346362623864626539383435643132633236666336393930303262322f30325f70726f64756374696f6e2e6970796e62&nwo=fastai%2Ffastbook&path=02_production.ipynb&repository_id=243838973&repository_type=Repository#Training-Your-Model,-and-Using-It-to-Clean-Your-Data)), when listing the images with the top loss, I got some pretty graphic pictures of dead bears I would have preferred to not face and that would be considered NSFW if I would be working in an office (blurred in the screenshot below).

![image](https://user-images.githubusercontent.com/2451004/92489409-08c82180-f1f0-11ea-8a8f-35bae64eb447.png)

That's of course an effect of using results from search engines for our training and I'm not blaming you or the course for this, but I personally wasn't prepared to see this. That may be something worth mentioning in the book when you're first discussing services that can be used for training. Maybe just a note "Be aware that using results from public search engine can yield graphics results", or something equivalent.

What do you think?

**Comment by jph00** [comment]
Sure will do. I'd never seen that in any of my testing.

**Comment by jph00** [comment]
Added now.
