### ISSUE TITLE
Chapter 7: name 'Mixup' is not defined

### ISSUE THREAD

**Issue by Quaterion** [fastai/fastbook#257]
In chapter 7 "Training a State-of-the-Art Model" section "Mixup" the code is not working as expected. Mixup is not found for Learner: 

    import fastbook
    fastbook.setup_book()
    from fastbook import *
    from fastai2.vision.all import *

    path = untar_data(URLs.IMAGENETTE)

    dblock = DataBlock(blocks=(ImageBlock(), CategoryBlock()),
                   get_items=get_image_files,
                   get_y=parent_label,
                   item_tfms=Resize(460),
                   batch_tfms=aug_transforms(size=224, min_scale=0.75))
    dls = dblock.dataloaders(path, bs=64)

    model = xresnet50()
    learn = Learner(dls, model, loss_func=CrossEntropyLossFlat(), 
                metrics=accuracy, cbs=Mixup)
    learn.fit_one_cycle(5, 3e-3)

    ---------------------------------------------------------------------------
    NameError                                 Traceback (most recent call last)
    <ipython-input-5-702ded874f78> in <module>
          1 model = xresnet50()
          2 learn = Learner(dls, model, loss_func=CrossEntropyLossFlat(), 
    ----> 3                 metrics=accuracy, cbs=Mixup)
          4 learn.fit_one_cycle(5, 3e-3)

    NameError: name 'Mixup' is not defined

I am using fastai2 version '0.0.30'

**Comment by TannerGilbert** [comment]
Mixup needs to instantiated like:

```python
mixup = MixUp(0.5)
```

then you can say ```cbs=mixup```

For more information check out: https://docs.fast.ai/callback.mixup#MixUp

**Comment by Quaterion** [comment]
Thank you! This was not mentioned in the text of the book!
