### ISSUE TITLE
Chapter 7: Confusion matrix of a model with mixup

### ISSUE THREAD

**Issue by Quaterion** [fastai/fastbook#259]
**The book does not show how to interpret a Learner with mixup. The standard way does not work:** 

    import fastbook
    fastbook.setup_book()
    from fastbook import *
    from fastai2.vision.all import *

    path = untar_data(URLs.IMAGENETTE)

    dblock = DataBlock(blocks=(ImageBlock(), CategoryBlock()),
                   get_items=get_image_files,
                   get_y=parent_label,
                   item_tfms=Resize(460),
                   batch_tfms=aug_transforms(size=224, min_scale=0.75))
    dls = dblock.dataloaders(path, bs=90)

    Mixup = MixUp(0.25)
    model = xresnet50()
    learn_test = Learner(dls, model, loss_func=CrossEntropyLossFlat(), 
                metrics=accuracy, cbs=Mixup)
    learn_test.fit_one_cycle(1, 3e-3)

    interp = ClassificationInterpretation.from_learner(learn_test.fit_one_cycle)
    interp.plot_confusion_matrix(figsize=(6,6), dpi=60)

---------------------------------------------------------------------------
  AssertionError                            Traceback (most recent call last)
<ipython-input-324-bcf4d0a8ce05> in <module>
  ----> 1 interp.plot_confusion_matrix(figsize=(6,6), dpi=60)

~/anaconda3/lib/python3.7/site-packages/fastai2/interpret.py in plot_confusion_matrix(self, normalize, title, cmap, norm_dec, plot_txt, **kwargs)
68         "Plot the confusion matrix, with `title` and using `cmap`."
69         # This function is mainly copied from the sklearn docs
---> 70         cm = self.confusion_matrix()
71         if normalize: cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
72         fig = plt.figure(**kwargs)

~/anaconda3/lib/python3.7/site-packages/fastai2/interpret.py in confusion_matrix(self)
60         "Confusion matrix as an `np.ndarray`."
61         x = torch.arange(0, len(self.vocab))
---> 62         d,t = flatten_check(self.decoded, self.targs)
63         cm = ((d==x[:,None]) & (t==x[:,None,None])).long().sum(2)
64         return to_np(cm)

~/anaconda3/lib/python3.7/site-packages/fastai2/torch_core.py in flatten_check(inp, targ)

~/anaconda3/lib/python3.7/site-packages/fastcore/test.py in test_eq(a, b)
30 
31 # Cell
---> 32 def test_eq(a,b):
  33     "`test` that `a==b`"
34     test(a,b,equals, '==')

~/anaconda3/lib/python3.7/site-packages/fastcore/test.py in test(a, b, cmp, cname)
20 # Cell
21 def test(a, b, cmp,cname=None):
  ---> 22     "`assert` that `cmp(a,b)`; display inputs and `cname or cmp.__name__` if it fails"
23     if cname is None: cname=cmp.__name__
24     assert cmp(a,b),f"{cname}:\n{a}\n{b}"

AssertionError: ==:
  90000
90

**The reason seems to be that the shapes of targs and decoded do not match for a Learner object with mixup (without using mixup it is fine by the way and plot_confusion_matrix() works ):** 

    interp.targs.shape
torch.Size([90])

    interp.decoded.shape
torch.Size([90, 1000])

    interp.decoded
tensor([[  5.4944,  11.8851,   6.1342,  ...,  -9.4419,  -9.9511,  -9.5237],
        [  6.4170,  12.1107,   6.0493,  ...,  -9.5812, -10.0529,  -9.8623],
        [ 12.4228,   5.4061,   4.0041,  ...,  -9.0347,  -9.8234,  -9.7119],
        ...,
        [  7.3852,  13.1206,   4.8565,  ...,  -9.6857, -10.0262,  -9.8459],
        [  7.9578,  14.2843,   4.4079,  ..., -10.6901, -11.3057, -10.9377],
        [ 11.3842,   5.5891,   4.7755,  ...,  -8.5168,  -8.0564,  -7.8670]])

**I do not know what the output of interp.decoded means. How can I get a confusion matrix from a model with mixup?** 

If this is the wrong place to ask the question please advise me where the question would fit better. Thanks!

**Comment by polyrand** [comment]
I had a similar problem. So far I found this works:

Create initial model:

```python
mixup = MixUp(0.4)

learn = cnn_learner(
    dls=dls,
    arch=models.resnet50,
    cbs=mixup,
)

learn.finetune(...)
```

Then save the learner:

```python
learn.save("trained_model")
```

And recreate the learner **without** MixUp and load the previous model:

```python
learn = cnn_learner(
    dls=dls,
    arch=models.resnet50,
)

learn.load("trained_model")

interp = ClassificationInterpretation.from_learner(learn)
# Continue with standard interpretation functions
```

Notice the [interpretation class](https://docs.fast.ai/interpret) needs a `Learner` object, in the example you provided you were calling the function `.fit_one_cycle`.

Something I haven't looked at is using the context manager `learn.removed_cbs()`:

https://forums.fast.ai/t/is-there-anyway-to-call-learn-get-preds-without-triggering-any-of-the-callbacks/64753

Maybe that works too.

**Comment by jph00** [comment]
We're not likely to add this to the book.
