### ISSUE TITLE
Indentation of bear_types loop in 02_production.ipynb 

### ISSUE THREAD

**Issue by bwbbfcb** [fastai/fastbook#261]
Hi! 

I believe this cell in 02_production.ipynb:- 

```
if not path.exists():
    path.mkdir()
    for o in bear_types:
        dest = (path/o)
        dest.mkdir(exist_ok=True)
        results = search_images_bing(key, f'{o} bear')
        download_images(dest, urls=results.attrgot('content_url'))
```

should be indented like this:-

```
if not path.exists():
    path.mkdir()
for o in bear_types:
    dest = (path/o)
    dest.mkdir(exist_ok=True)
    results = search_images_bing(key, f'{o} bear')
    download_images(dest, urls=results.attrgot('content_url'))
```

I've not used Python before so I didn't identify the problem straight away. I'm sure that most Python people will figure it out pretty quickly, but I thought I'd let you know anyway.

Thanks for the free resources!!!

**Comment by TannerGilbert** [comment]
I think it is fine as it is since, for this example, you really only want to download the images once. If you would run the could you suggested multiple times, it would always download additional images, which I don't think is intended for this application.

**Comment by android-kunjapppan** [comment]
No need to intend. It is fine as it is
