### ISSUE TITLE
Example for multi-label classification using TabularPandas

### ISSUE THREAD

**Issue by soerendip** [fastai/fastbook#266]
It is not really explained how to use TabularPandas on classification problems. Apparently, when the targets are encoded as 0 and 1, a regression task is assumed and `y_block = CategoryBlock` should be passed to `tabular_learner` as explained [here](https://docs.fast.ai/tutorial.tabular). However, it is unclear where to add `y_block`. In `tabular_learner` or `to.dataloaders` or `TabularPandas`?

When adding it to the `tabular_learner` the loss correctly changes to Flattened of CrossEntropyLoss, but then the model cannot be trained anymore: 

    ValueError: Expected input batch_size (64) to match target batch_size (13184).

Somehow the target batch_size needs to be adjusted (maybe specific to multi-label problems).

**Comment by soerendip** [comment]
Can CategoryBlock handle vectors?

**Comment by TannerGilbert** [comment]
You need to set the y_block argument for `TabularPandas` to `CategoryBlock```.

For an example check out: https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0/blob/master/Tabular%20Notebooks/01_Adults.ipynb

**Comment by soerendip** [comment]
That apparently does not work for multi-label data the elements of y are vectors [0,1 ,0 ,0, 1] each element indicating the presence of a certain label. I.e. Y is a 2D matrix. Setting `y_block=CategoryBlock` in tabluar learner than throws:

> ValueError: Target size (torch.Size([13184])) must be the same as input size (torch.Size([128]))

So, the target or prediction seems to be flattened while the other is not! This is for a batch size of 64 and `len(y_names)=206`

**Comment by TannerGilbert** [comment]
There is also a `MultiCategoryBlock`. You can find the documentation [here](https://docs.fast.ai/data.block#MultiCategoryBlock).

**Comment by jcuenod** [comment]
The url is now https://docs.fast.ai/data.block.html#multicategoryblock

I'm also having trouble with this. A tutorial on multi-label classification would be helpful. I resolved the `ValueError` by one hot encoding my ys and setting n_out appropriately but I'm running into other problems loading my model now (errors about columns missing from training data that are present in the training data).
