### ISSUE TITLE
Failing cells in 05_pet_breeds.ipynb

### ISSUE THREAD

**Issue by erogers-utilant** [fastai/fastbook#267]
# Multiple failing cells in `05_pet_breeds.ipynb`

## Error on code cell 12:
The first error I wanted to point out is currently visible as output to the code cell included on [the current copy on master](https://github.com/fastai/fastbook/blob/c6322c6/05_pet_breeds.ipynb) -- note the `RunTimeError` on the output to the 12th code cell.

### Steps to reproduce:
None needed. Error is currently printed in output on master

## Error when attempting to run code cell 9:

I'm also experiencing an error earlier when I try to run the 9th code cell:
```python
pets = DataBlock(blocks = (ImageBlock, CategoryBlock),
                 get_items=get_image_files, 
                 splitter=RandomSplitter(seed=42),
                 get_y=using_attr(RegexLabeller(r'(.+)_\d+.jpg$'), 'name'),
                 item_tfms=Resize(460),
                 batch_tfms=aug_transforms(size=224, min_scale=0.75))
dls = pets.dataloaders(path/"images")
```
```
Could not do one pass in your dataloader, there is something wrong in it
```

### Steps to reproduce:
1. Follow [the instructions to start the FastaiSageMakerStack on AWS](https://course.fast.ai/start_sagemaker). (I used us-east-1 with an `ml.p2.xlarge` instance type.)
2. Open Jupyter for the SageMaker Instance created.
3. Open `05_pet_breeds.ipynb`.
4. Set the kernel to `fastai`.
5. Cell > Run All

---

Thanks for putting together all these resources. It's clear that a great amount of thought and care has gone into this book. Let me know if there's any way I can help further debug this issue.

**Comment by TannerGilbert** [comment]
Actually this error in cell 12 is meant to exist to show the power of the `.summary` method if you make an error while building your `DataBlock` as mentioned in the text above the cell.

Also cell 9 runs without any error when I run it in Google Colab
