### ISSUE TITLE
    Sorry, something went wrong. Reload?

### ISSUE THREAD

**Issue by pyanishjain** [fastai/fastbook#275]
it always shows this when I open the notebook for the first time and 4  to 5 times i have to reload it

**Comment by TannerGilbert** [comment]
This is a issue with Github and not related to this repository. If you want to follow up further check out jupyter/notebook#3555.

**Comment by abhinav-TB** [comment]
This is because GitHub sometimes fails to load large files, try downloading the notebook to avoid this.
