### ISSUE TITLE
Suggestion: more transparent functions in code

### ISSUE THREAD

**Issue by grayskripko** [fastai/fastbook#277]
I can't remember the correct name for it in coding theory but the idea is not to use variables from the global scope. I've watched the 4th video and revising the material with 04_mnist_basecs.ipynb. It was hard to deeply understand the structure of dependencies between elements here:

```
def train_epoch(model, lr, params):
    for xb,yb in dl:  # oh, so we need X and Y in train_epoch() too! But we get them from global scope implicitly
```

and here

```
def linear1(xb): return xb@weights + bias
# we need weights and bias as well as xb to calculate linear1
```
and so forth.

I mean moving through the lecture sometimes I need to go back to remember what exactly is `linear1()`. 
I need to read the whole function to understand its real dependencies. Such distractions can cost a lot of student mind resources.

**Comment by jph00** [comment]
This is how Jupyter works.
