### ISSUE TITLE
Use RISE to turn this book into slides

### ISSUE THREAD

**Issue by Riezebos** [fastai/fastbook#285]
I'm working through this great book and the course and I noticed that the whole fastai ecosystem seems to be built on jupyter. After seeing nbdev, fastpages and fastbook I have a strong feeling that there is just one thing left to be jupyterized: slides. I just wanted to share with you the following library in case this is the missing puzzle piece to move more of fastai into jupyter:

https://github.com/damianavila/RISE

I am not affiliated, but I believe it might be possible to use this to make fastbook not just a book and a set of interactive notebooks but also the actual slides of the fastai course simultaneously.

**Comment by jph00** [comment]
Many thanks.
