### ISSUE TITLE
I would like to translate the book's README to Bengali

### ISSUE THREAD

**Issue by ghosh-r** [fastai/fastbook#290]
I just saw a Korean translation to the README of the book, and **I want to add a Bengali translation** which will help native Bengali speakers. **I am a native Bengali speaker proficient in English** and have been speaking in both languages from a young age.

**I am learning from fast.ai for a few months** now, and I have completed Andrew Ng's Machine Learning course and IBM's Data Science Professional Certification- so I have the technical background as well.

Should I go ahead and create a PR for it?

**Comment by TannerGilbert** [comment]
Yes sure. Every contribution is welcome

**Comment by ghosh-r** [comment]
Thanks, I will get started!
