### ISSUE TITLE
04_mnist_basics.ipynb: the mean_3 should be corrected as mean3!

### ISSUE THREAD

**Issue by newuse2001** [fastai/fastbook#317]
This is the same value we previously calculated for the distance between these two images, the ideal 3 mean_3 and the arbitrary sample 3 a_3, which are both single-image tensors with a shape of [28,28].

This sentence has a mistake. I think the mean_3 should be corrected as mean3.  since the variable of the mnist_distance(a_3, mean3) is mean3.

**Comment by jph00** [comment]
Thanks.
