### ISSUE TITLE
09_tablular: SVG output of dtreeviz is corrupted

### ISSUE THREAD

**Issue by Qumeric** [fastai/fastbook#326]
SVG image generated by dtreeviz is one of the snippets is corrupted, so browser can't show it. See screenshots attached. Firefox also throws an error doesn't show everything at all
<img width="1238" alt="Screenshot 2020-11-04 at 17 24 51" src="https://user-images.githubusercontent.com/3511113/98123535-e417bf80-1ea9-11eb-8dbc-b74862319bb6.png">
<img width="1513" alt="Screenshot 2020-11-04 at 17 25 09" src="https://user-images.githubusercontent.com/3511113/98123543-e5e18300-1ea9-11eb-885d-c4547b02c673.png">

**Comment by Qumeric** [comment]
Please note that the second screenshot is the result of opening the image directly, not how it looks in the notebook.

**Comment by jph00** [comment]
Suggest you open an issue in the dtreeviz repo
