### ISSUE TITLE
UnicodeEncodeError from TextBlock.from_folder on windows10 

### ISSUE THREAD

**Issue by rajendra-ml** [fastai/fastbook#328]
I am trying to run this notebook with slight modification.  The modification is that text files are non-english (marathi) and utf-8 encoded, extracted from wikisource.

Following is code I wanted to run:
`get_texts = partial(get_text_files, folders=['data_txt'])
dls_lm = DataBlock(
    blocks=TextBlock.from_folder(path, is_lm=True, tok=tkn, n_workers=0, skip_if_exists=False),
    get_items=get_texts, splitter=RandomSplitter(0.1)
).dataloaders(path, path=path, bs=128, seq_len=80)
`

The error I get is:
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-9: character maps to <undefined>
Full error trace is given below.
 It seems that the 
In C:\ProgramData\Anaconda3\lib\pathlib.py  write_text  function (f.write(data)) is somehow not getting utf-8 encoding.

Please help!

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-33-4506954ad164> in <module>
      1 dls_lm = DataBlock(
 
----> 2    blocks=TextBlock.from_folder(path, is_lm=True, tok=tkn, n_workers=0, skip_if_exists=False),
      3     get_items=get_texts, splitter=RandomSplitter(0.1)
      4 ).dataloaders(path, path=path, bs=128, seq_len=80)

C:\ProgramData\Anaconda3\lib\site-packages\fastai\text\data.py in from_folder(cls, path, vocab, is_lm, seq_len, backwards, min_freq, max_vocab, **kwargs)
    210     def from_folder(cls, path, vocab=None, is_lm=False, seq_len=72, backwards=False, min_freq=3, max_vocab=60000, **kwargs):
    211         "Build a `TextBlock` from a `path`"
--> 212         return cls(Tokenizer.from_folder(path, **kwargs), vocab=vocab, is_lm=is_lm, seq_len=seq_len,
    213                    backwards=backwards, min_freq=min_freq, max_vocab=max_vocab)
    214 

C:\ProgramData\Anaconda3\lib\site-packages\fastai\text\core.py in from_folder(cls, path, tok, rules, **kwargs)
    275         path = Path(path)
    276         if tok is None: tok = WordTokenizer()
--> 277         output_dir = tokenize_folder(path, tok=tok, rules=rules, **kwargs)
    278         res = cls(tok, counter=load_pickle(output_dir/fn_counter_pkl),
    279                   lengths=load_pickle(output_dir/fn_lengths_pkl), rules=rules, mode='folder')

C:\ProgramData\Anaconda3\lib\site-packages\fastai\text\core.py in tokenize_folder(path, extensions, folders, output_dir, skip_if_exists, **kwargs)
    182     files = get_files(path, extensions=extensions, recurse=True, folders=folders)
    183     def _f(i,output_dir): return output_dir/files[i].relative_to(path)
--> 184     return _tokenize_files(_f, files, path, skip_if_exists=skip_if_exists, **kwargs)
    185 
    186 # Cell

C:\ProgramData\Anaconda3\lib\site-packages\fastai\text\core.py in _tokenize_files(func, files, path, output_dir, output_names, n_workers, rules, tok, encoding, skip_if_exists)
    167     for i,tok in parallel_tokenize(files, tok, rules, n_workers=n_workers):
    168         out = func(i,output_dir)
--> 169         out.mk_write(' '.join(tok))
    170         lengths[str(files[i].relative_to(path))] = len(tok)
    171         counter.update(tok)

C:\ProgramData\Anaconda3\lib\site-packages\fastcore\xtras.py in mk_write(self, data, encoding, errors, mode)
     98     "Make all parent dirs of `self`"
     99     self.parent.mkdir(exist_ok=True, parents=True, mode=mode)
--> 100     self.write_text(data, encoding=encoding, errors=errors)
    101 
    102 # Cell

C:\ProgramData\Anaconda3\lib\pathlib.py in write_text(self, data, encoding, errors)
   1250                             data.__class__.__name__)
   1251         with self.open(mode='w', encoding=encoding, errors=errors) as f:
-> 1252             return f.write(data)
   1253 
   1254     def touch(self, mode=0o666, exist_ok=True):

C:\ProgramData\Anaconda3\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-9: character maps to <undefined>

**Comment by jph00** [comment]
Sorry we don't support running on windows.
