### ISSUE TITLE
Bing image search API changing causes issues on search_images_bing 'PermissionDenied'

### ISSUE THREAD

**Issue by decyborg** [fastai/fastbook#331]
Hi folks,

I'm currently working my way through lesson 2 of the book and I'm facing an issue while trying to download the images.
Apparently Microsoft is reestructuring their bing API and keeping it out of their cognitive services, they've also changed the URL to use for the query:
https://docs.microsoft.com/en-us/azure/cognitive-services/Bing-Image-Search/overview

> Bing Search APIs are moving from Cognitive Services to Bing Search Services. Starting October 30, 2020, any new instances of Bing Search need to be provisioned following the process documented here. Bing Search APIs provisioned using Cognitive Services will be supported for the next three years or until the end of your Enterprise Agreement, whichever happens first. For migration instructions, see Bing Search Services.

Seems like they are changing from what the code is currently using:
     51     client = api('https://api.cognitive.microsoft.com', auth(key))
To:
https://api.bing.microsoft.com/v7.0/search

I'm just getting started with Jupyter notebooks and I'm trying to figure out how to update the library gradient is using, to try and fix this issue, but in the meantime I thought I might report it, seems like a workaround has already been found in the forums:

https://forums.fast.ai/t/02-production-permissiondenied-error/65823/28

Cheers!

**Comment by joshkraft** [comment]
FYI, I went ahead and create a pull request for this: https://github.com/fastai/fastbook/pull/333

**Comment by jph00** [comment]
Fixed now
