### ISSUE TITLE
09_tabular issues

### ISSUE THREAD

**Issue by adamfarquhar** [fastai/fastbook#336]
There appear to be several issues in fastbook/clean/09_Tabular.ipynb that have been reported in the forum, but not in github issues. This issue aggregates them together.

I confirmed that all of them occur in the version included in the fastdotai/fastai-course docker image of 19-Nov-2020. I presume that the official docker image version of the course should run through cleanly without any errors.

- Some supporting modules are not installed: `pip install kaggle waterfallcharts treeinterpreter dtreeviz` ([forum article](https://forums.fast.ai/t/draw-tree-in-09-tabular-got-truncated/79152/5))
- Downloading the kaggle file bluebook-for-bulldozers does not appear to work from python. There are multiple reports of this (including [here](https://forums.fast.ai/t/kaggle-api-issue/77213)) with the workaround being to download manually via the browser or via the commandline (`kaggle competitions download -c bluebook-for-bulldozers`). 
- The code to download also fails because it tries to create a directory but needs a `parents=True` added to `path.mkdir` ([see](https://forums.fast.ai/t/lesson-7-official-topic/69896/327)).
- The load/save pickle method should be changed to `load_pickle`/`save_pickle` (reported a couple of times on the forum including [here](https://forums.fast.ai/t/09-tabular-ipynb-error-in-executing-code-path-to-pkl-save-to/82180/2))
-  `m_rmse(m, xs_filt2, y_filt), m_rmse(m2, valid_xs_time2, valid_y)` raises an error. `xs_filt2` should be `xs_filt`. as in `m_rmse(m, xs_filt, y_filt), m_rmse(m2, valid_xs_time2, valid_y)`  ([see here](https://forums.fast.ai/t/error-in-chapter-9-lesson-7/77944)).
- `procs_nn = [Categorify, FillMissing, Normalize]` causes an error in the following line. The suggested work-around is to remove `Normalize` from the list ([see here](https://forums.fast.ai/t/09-tabular-value-error-unable-to-coerce-to-series-length-must-be-1-given-0/80580/8))

**Comment by jph00** [comment]
Many thanks for the thorough issue. I've just gone the nb from top to bottom and it's all working now. Please open a new issue if you find anything not working.
