### ISSUE TITLE
Wrong syntax in search_images_bing

### ISSUE THREAD

**Issue by Rob192** [fastai/fastbook#343]
Hello,
I am having trouble using the lesson 04. In the first input when I try to run the imports :
```python
#hide
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()
```

I am having the following error: 
```python
File "/usr/local/lib/python3.6/dist-packages/fastbook/__init__.py", line 45
    def search_images_bing(key,earch_images_bing(key, term, min_sz=128, max_images=150):
SyntaxError: invalid syntax
````
Could it be a typo in the last release ?

**Comment by voddan** [comment]
Same problem for me. Yesterday it worked, but I had to reinstall my VM, and now it is broken.

> $ yolk -V fastbook
> fastbook 0.0.15

**Comment by voddan** [comment]
Workaround: modify the first cell of each notebook to be 

> #hide
> !pip install -Uqq fastbook==0.0.14
> import fastbook
> fastbook.setup_book()

**Comment by jph00** [comment]
Fixed now - sorry about that

**Comment by voddan** [comment]
@jph00 Which version contains the fix?

**Comment by jph00** [comment]
0.0.16. It only just found it's way onto pypi.
