### ISSUE TITLE
search_images_ddg in paperspace is not working

### ISSUE THREAD

**Issue by samjoy** [fastai/fastbook#358]
When I try to use search_images_ddg in paperspace using the fastai container, its not working. I am getting an error stating the function is not defined.

**Comment by caush** [comment]
Try something like 

    from utils import 
    urls = search_images_ddg(u'macao parrot', max_n=200)

**Comment by samjoy** [comment]
yeah that works.
Thanks
Is it expected that the images returned from download_images will be of varying sizes?

**Comment by jeffbmartinez** [comment]
In case someone else stumbles up on this, my problem is that I was using the `clean/` version of the notebook and `utils.py` doesn't exist in the folder.
