### ISSUE TITLE
01_intro.ipynb (clean): NameError: name 'image_cat' is not defined

### ISSUE THREAD

**Issue by yonathan06** [fastai/fastbook#361]
```python
img = PILImage.create(image_cat())
img.to_thumb(192)
```

`image_cat()` is not defined, can't see it in the notebook

**Comment by SBDEVELOP** [comment]
You can add a new cell and run the following:
`image_cat??`
This will provide you some details regarding its implementation origin.

`Signature: image_cat()`
`Docstring: <no docstring>`
`Source:    def image_cat (): return BytesIO(pkgutil.get_data('fastbook', 'images/cat.jpg'))`
`File:      <your local path>\fastbook\__init__.py`
`Type:      function`

**Comment by prosoitos** [comment]
`image_cat??` returns:

> Object `image_cat` not found.

Wondering whether this sidebar got broken by some update at some point?
