### ISSUE TITLE
`pip install fastbook` failing on Google Colab

### ISSUE THREAD

**Issue by MaximumEndurance** [fastai/fastbook#424]
`!pip install -Uqq fastbook` is failing on Google colab with the following error - 

`ERROR: torchtext 0.9.0 has requirement torch==1.8.0, but you'll have torch 1.7.1 which is incompatible.`

Tried that on a fresh notebook as well. [Link to Colab Notebook](https://colab.research.google.com/drive/1sCKBTDaVepo4svLaUF0xGeyMz5QYfVIB?usp=sharing)

**Comment by halfer53** [comment]
Second this. Had similar issue as well

**Comment by tirthvyas-tk-labs** [comment]
Try this, it worked for me!
`!pip install fastai --upgrade`

Successfully uninstalled fastai-1.0.61
Successfully installed fastai-2.2.7 fastcore-1.3.19 torch-1.7.1 torchvision-0.8.2

**Comment by Rebolforces** [comment]
@jph00 can be closed. Is working.
