### ISSUE TITLE
Possibly erroneous details in Ch 4 SGD section

### ISSUE THREAD

**Issue by duanasq** [fastai/fastbook#434]
Hi I'm a newbie so I am probably just confused, but in the section [An End-to-End SGD Example](https://github.com/fastai/fastbook/blob/master/04_mnist_basics.ipynb):

```
def mse(preds, targets): return ((preds-targets)**2).mean().sqrt()
```
^ This seems like the Root Mean Squared Error, not the Mean Squared Error?

And here - that loss (circled in orange) looks huge? I expect it to be close to the average absolute error which (just eyeballing it) looks to be around 150?
![Screenshot 2021-04-13 at 8 27 10 am](https://user-images.githubusercontent.com/74888616/114638446-f6c2da00-9d0e-11eb-9e1f-856768f4151e.png)

Thx! Love this course!

**Comment by zxul767** [comment]
Related: https://github.com/fastai/fastbook/issues/454

**Comment by tmabraham** [comment]
@jph00 can be closed
