### ISSUE TITLE
where is the setup_book() code?

### ISSUE THREAD

**Issue by d3netxer** [fastai/fastbook#440]
In fastai notebooks fastbook.setup_book() is often run. Where is it running this code from? I cannot not find the setup_book function in this repo.

**Comment by idhn9999** [comment]
Just do a question mark to see

![image](https://user-images.githubusercontent.com/83121503/117579741-e975f100-b0fc-11eb-83e4-a16889e52546.png)

**Comment by d3netxer** [comment]
ok thanks!

**Comment by xzmeng** [comment]
https://github.com/fastai/course20/tree/master/fastbook
