### ISSUE TITLE
GAN notebooks were not ported to the newest version of fastai

### ISSUE THREAD

**Issue by squassina** [fastai/fastbook#447]
I just started working with GAN and Fastai and I had some trouble finding some examples of notebooks working with the latest version of fastai. Is there a reason for that?

I run an simple experiment based on the original one in [fastai/course-v3](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson7-wgan.ipynb) and the fastai docs and pushed to my [repo](https://github.com/squassina/fastai_gan_sample)

I don't recall a chapter related to GAN in the latest version of the book, so let me know should I open a PR to this repo so we could find everything in one place.

**Comment by tmabraham** [comment]
@squassina there is some support of GANs in the current version of fastai: https://docs.fast.ai/vision.gan
If you have questions about it, please open an issue in the main repo (https://github.com/fastai/fastai)

@jph00 can be closed...
