### ISSUE TITLE
Ch. 10_nlp: Typo in Subword Tokenization's subword method

### ISSUE THREAD

**Issue by tylertaewook** [fastai/fastbook#457]
```python
def subword(sz):
    sp = SubwordTokenizer(vocab_sz=sz)
    sp.setup(txts)
    return ' '.join(first(sp([txt]))[:40])
```

The last line should be `txts` instead of `txt` to avoid not defined error.

**Comment by zhaoshaojun** [comment]
This is not an issue, and you should be able to run the notebook without issues. 'txts' refers to the corpus that is used for training the tokenizer, and 'txt' refers to some input to be tokenized. They are not the same thing therefore should not be change to either 'txts' or 'txt'.

**Comment by zhaoshaojun** [comment]
Please close this issues.
