### ISSUE TITLE
Not sure, is this wrong in chapter 5(0.999 is ten times more than 0.99)?

### ISSUE THREAD

**Issue by JonathanSum** [fastai/fastbook#46]
![image](https://user-images.githubusercontent.com/21982975/76238083-88971400-61ec-11ea-96a9-da1f18eaab2e.png)

Is it a typo for "s:"?
![image](https://user-images.githubusercontent.com/21982975/76239653-2db2ec00-61ef-11ea-9382-db7f0f2f8b58.png)

**Comment by bradsaracik** [comment]
I'm looking at this with no context, but It'll be this:  If you get 99 in 100 right, you get 1 in 100 i.e. 10 in 1000 wrong. If you get 999 in 1000 right, you get 1 wrong. 10 times 1.
