### ISSUE TITLE
Should I read the "accuracy" defined in 04_mnist_basics.ipynb as "recall"

### ISSUE THREAD

**Issue by SantiDu** [fastai/fastbook#470]
In binary classification, the accuracy is defined as (tp + tn) / (tp + fp + tn + fn), in the minst example, the "accuracy" seems to be (tp / (tp + fn) + tn / (tn + fp)) / 2 if I am correct:

```python
accuracy_3s =      is_3(valid_3_tens).float() .mean()
accuracy_7s = (1 - is_3(valid_7_tens).float()).mean()

accuracy_3s,accuracy_7s,(accuracy_3s+accuracy_7s)/2
```

So it looks like average recall to me. I know Jeremy is teaching the class from a up-bottom approach, maybe this is the reason he skipped the fuzz.

**Comment by zxul767** [comment]
Indeed, `is_3(valid_3_tens).float().mean()` is computing recall. I too assume the term `accuracy` was used in a more colloquial sense simply because the focus of the section was not model metrics.
