### ISSUE TITLE
fastbook doesn't have graphviz in requirements, so it fails

### ISSUE THREAD

**Issue by surak** [fastai/fastbook#487]
/home/strube1/fastai/fast-venv/lib/python3.8/site-packages/fastbook/__init__.py:19: UserWarning: Missing `graphviz` - please run `conda install fastbook`
  except ModuleNotFoundError: warn("Missing `graphviz` - please run `conda install fastbook`")

**Comment by pwolter** [comment]
Graphviz is in the `requirements.txt` file:

```
fastai>=2.0.0
graphviz
ipywidgets
matplotlib
nbdev>=0.2.12
pandas
scikit_learn
azure-cognitiveservices-search-imagesearch
sentencepiece
```

You may want to run `pip install -r requirements.txt`  in the console if you are running the notebooks locally or `!pip install -r requirements` in the first cell of your notebooks if you are running it in Colab or Paperspace (as it is my case).

Maybe adding this line into the first Notebook will make sense?

**Comment by surak** [comment]
You are absolutely correct. That makes sense, as I was following the instructions.

**Comment by jph00** [comment]
fixed now
