### ISSUE TITLE
Error in chapter 10

### ISSUE THREAD

**Issue by swaroopkml96** [fastai/fastbook#5]
There is a mistake in the notebook for chapter 10 which makes the sentence mean the opposite of the authors' intent.

Section 1.3.3. Last sentence of the paragraph following the 3rd cell:
The line
```
The model not without the final layer is
called the encoder.
```
should be replaced by either
```
The model without the final layer is
called the encoder.
```
or
```
The model not including the final layer is
called the encoder.
```

**Comment by jph00** [comment]
Fixed, thanks. Feel free to send a PR if you see other issues, BTW.
