### ISSUE TITLE
Inconsistent results running an unchanged 4th chapter notebook on paperspace.

### ISSUE THREAD

**Issue by yuvallangerontheroad** [fastai/fastbook#500]
I have loaded the "Paperspace + Fast.AI" notebook on https://console.paperspace.com/ and ran all of the cells in the full book ipynb file. I get this, which means something went very wrong somewhere:

![Screenshot from 2022-02-15 10-09-46](https://user-images.githubusercontent.com/5238393/154043298-44caa9e7-dde1-42d1-903f-7dd36045b0dd.png)

I did not change any of the default settings when creating the notebook. All the notebook cells are unchanged.

Many thanks!

**Comment by tmabraham** [comment]
@jph00 can be closed
