### ISSUE TITLE
CUDA on Windows errror in Intro

### ISSUE THREAD

**Issue by pwichmann** [fastai/fastbook#51]
Totally likely that this is my incompetence. But it seems that the code in the Intro notebook does not work out of the box on Windows. This would probably at least require a warning for (the few) Windows users among the book buyers.

The first little classifier fails with:

![image](https://user-images.githubusercontent.com/13521375/76520086-83db9580-6462-11ea-8f28-7ea4a2bda1b2.png)

This is the most related info I could find:
https://pytorch.org/docs/stable/notes/windows.html#cuda-ipc-operations

**Comment by bradsaracik** [comment]
can you take that to the forum as requested on the frontpage readme?
https://forums.fast.ai/c/fastai-users/fastai-v2

**Comment by pwichmann** [comment]
Sorry.
