### ISSUE TITLE
Do we have BERT or Ernie as pretained NLP model for use with FastAI?

### ISSUE THREAD

**Issue by franva** [fastai/fastbook#512]
Hi there,

I have previously used the NLP function with FastAI and found it's super easy to use and the accuracy is also great.

2 years later which is now, I finally got a chance to use do NLP for my work. I'm thinking of using FastAI to do it.

I just checked the current trend and found the transformer arch has ruled the world, especially BERT and ErNIE.

So I was wondering what's the arch FastAI NLP uses, and found it uses Recurrent NN which is a classical model but not the latest tech.

just wondering, do we have a plan for including the BERT and Ernie models to FastAI?

**Comment by tmabraham** [comment]
You can use such models through HuggingFace Transformers and it can be integrated with fastai using packages like [blurr](https://github.com/ohmeow/blurr)

In the future, please ask any questions you have about using fastai in the forums at https://forums.fast.ai

The issues here are mainly to raise any problems or bugs with the book notebooks. 

@jph00 you can close
