### ISSUE TITLE
Spelling error: Chapter 8, replace "twice as bit" with "twice as big"

### ISSUE THREAD

**Issue by StevenBorg** [fastai/fastbook#52]
", we can just make it twice as bit, so we" includes a spelling error.

Note: I've been doing these through pull requests, but there are enough duplicate corrections piling up that I feel it's not a good place any longer.  Should I move to issues?  Alternatively, if contributors could create meaningful PR titles and comments it would be easier to see if the fixes have already been committed.

**Comment by bradsaracik** [comment]
FYI Steven - the PRs have been merged - so if you get a notification from this and this hasn't been sorted on master ...

**Comment by jph00** [comment]
Fixed in private branch - thanks.
