### ISSUE TITLE
08_collab has a wrong sentence

### ISSUE THREAD

**Issue by hantusk** [fastai/fastbook#88]
> It tells us not just whether a movie is of a kind that people tend not to enjoy watching, but that people type like watching it even if it is of a kind that they would otherwise enjoy! 

Should be

It tells us not just whether a movie is of a kind that people tend not to enjoy watching, but that people type **do not** like watching it even if it is of a kind that they would otherwise enjoy!

**Comment by sgugger** [comment]
Thanks for flagging, should be fixed now!
