### ISSUE TITLE
It's  The Oxford-IIIT Pet Dataset not Oxford-IIT Pet Dataset 

### ISSUE THREAD

**Issue by amitjslearn** [fastai/fastbook#92]
It's IIIT and not IIT. IIT and IIIT both are different Universities.
![image](https://user-images.githubusercontent.com/27467368/78926203-4c402780-7aba-11ea-8033-578bb3be0c2a.png)

**Comment by joe-bender** [comment]
I have made a PR fixing this, #107

**Comment by sgugger** [comment]
Fixed by #107
