### ISSUE TITLE
Continuity of text in chapter 2

### ISSUE THREAD

**Issue by Geethasaikrishna** [fastai/fastbook#94]
> We often talk to people who overestimate both the constraints, and the capabilities of deep learning. Both of these can be problems: underestimating the capabilities means that you might not even try things which could be very beneficial; underestimating the constraints might mean that you fail to consider and react to important issues.

**Issue:**  : In the above text, seems like authors are trying to say- _We often talk to people who **underestimate**_, but actual text says **overestimate**. We might have to correct it if it's the case ..:)

I might be wrong here in inferring it incorrectly, but somehow I feel what text is trying to say and what actually is present is different

**Comment by sgugger** [comment]
Fixed, thanks for flagging!

**Comment by Geethasaikrishna** [comment]
Thank you for the book and course ❤️
