### ISSUE TITLE
CAM chapter.  class selected for plot

### ISSUE THREAD

**Issue by qAp** [fastai/fastbook#97]
Hi
Should the class selected for this plot be 1 instead of 0, since `dls.train.vocab` is `[False, True]` with `True` for a cat?

<img width="486" alt="Screen Shot 2020-04-10 at 14 05 14" src="https://user-images.githubusercontent.com/2902346/79050381-3a968580-7c5c-11ea-84a0-71a0dc86e02e.png">

<img width="433" alt="Screen Shot 2020-04-10 at 14 05 30" src="https://user-images.githubusercontent.com/2902346/79050385-408c6680-7c5c-11ea-9472-e7f0264b4d40.png">

**Comment by sgugger** [comment]
Indeed it should, thanks for flagging!
