### ISSUE TITLE
Can I translate it to Chinese?

### ISSUE THREAD

**Issue by LXYTSOS** [fastai/fastbook#98]
Can I translate it to Chinese in my GitHub repo as a study material? of course not for commercial use.

**Comment by marylicious** [comment]
I'm interested too in translating it to Spanish

**Comment by awalther** [comment]
I could translate to German.

**Comment by Mynkxb** [comment]
Can I Translate it into French ?

**Comment by nolimits-sagar** [comment]
I am interested to translate these notebooks in Marathi, for study purposes. Can I ?

**Comment by jph00** [comment]
I'm not sure that's an option since it's published by O'Reilly. Feel free to ask them though!
